### ISSUE TITLE
请问是否有方法支持不同任务间共享上下文信息呢？

### ISSUE THREAD

**Issue by piratf** [zhshch2002/gospider#1]
一些场景需要配合父页面的信息来发起新的任务访问和解析子页面，感觉用闭包引用比较不直观以及要保护引用变量，如果能直接有个共享的 ctx 记录一下信息会不会更方便一点。

**Comment by zhshch2002** [comment]
`Context` 有一个 `Meta` 是用来在两个Task之间传递参数的。

**Comment by piratf** [comment]
> `Context` 有一个 `Meta` 是用来在两个Task之间传递参数的。

多谢，看 SeedTask 的实现里，会直接创建一个空的 Meta，我应该如何使用这个 Meta 字段来实现参数传递呢？（能否提供一个例子呢）

**Comment by zhshch2002** [comment]
meta没有设计在两个task之间传输的接口。我会尽快加入这个功能。

**Comment by zhshch2002** [comment]
参考 https://github.com/zhshch2002/gospider/blob/master/context.go 的实现，在一个context里设置meta，再从这个ctx创建新的Task，meta会被传递到新的Task。
