### ISSUE TITLE
请大佬关于Meta问题

### ISSUE THREAD

**Issue by lakevilladom** [zhshch2002/gospider#6]
比如在A页面爬取到了"标题"，"URL"字段，然后把URL通过addtask添加到爬取任务成为任务X，同时希望把标题字段通过Meta也传递到任务X中,然后在处理任务X的response的同时在把上面的的"标题"字段再取出来，有方法实现吗

**Comment by zhshch2002** [comment]
在A页面的任务里，AddTask之前对任务A对Meta设置标题字段。AddTask之后，新的任务X会把父任务的Meta拷贝过来。

参考：
- https://wiki.xzhsh.ch/gospider/#%E6%96%B0%E4%BB%BB%E5%8A%A1%E5%92%8Cmeta
- https://github.com/zhshch2002/gospider/blob/6bbb42e22665157329d23b487208f76febb326f8/task.go#L33

**Comment by lakevilladom** [comment]
`t.Meta["form"] = t.Req.URL`，是这个吗，
这个能不能也提供AddMeta、AddMetas的方法

**Comment by zhshch2002** [comment]
是这个。

写法上倒是没问题，但是设置Meta本身是赋值过程，没有其他的操作要做或者Hook要调用。直接操作Meta这个map也希望表达这一点。
